name: Android CI - Build and Firebase App Distribution

on:
  workflow_dispatch: {}
  push:
    branches: [ main, master ]
    paths:
      - 'android-app/**'
      - 'core/**'
      - '.github/workflows/android-firebase.yml'
      - 'build.gradle'
      - 'settings.gradle'
      - 'gradle.properties'

jobs:
  build-and-distribute:
    runs-on: ubuntu-latest
    env:
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_TESTERS: ${{ secrets.FIREBASE_TESTERS }} # comma-separated emails (optional)
      FIREBASE_GROUPS: ${{ secrets.FIREBASE_GROUPS }}   # comma-separated group aliases (optional)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0

      - name: Set up Gradle 8.2
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.2

      - name: Prepare Firebase service account
        if: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON != '' }}
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}" > $GITHUB_WORKSPACE/firebase-sa.json
          echo "FIREBASE_CREDENTIALS=$GITHUB_WORKSPACE/firebase-sa.json" >> $GITHUB_ENV

      - name: Build Debug APK
        run: gradle :android-app:assembleDebug --no-daemon

      - name: Upload to Firebase App Distribution (Debug)
        if: ${{ env.FIREBASE_APP_ID != '' }}
        run: gradle :android-app:appDistributionUploadDebug --no-daemon